"""change str to date work exprerience table

Revision ID: 03718c7b3328
Revises: deca24e15a01
Create Date: 2026-04-01 23:06:15.498076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03718c7b3328'
down_revision: Union[str, Sequence[str], None] = 'deca24e15a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'start_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='start_date::date')

    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='end_date::date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_experiences', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('work_experiences', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
