"""add jsonb and vector to documents

Revision ID: b0e7304861a8
Revises: d1464b08ea76
Create Date: 2026-03-06 23:47:40.566021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b0e7304861a8'
down_revision: Union[str, Sequence[str], None] = 'd1464b08ea76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding')
    op.drop_column('documents', 'parsed_json')
    # ### end Alembic commands ###
