"""change candidate id can be null in application table

Revision ID: deca24e15a01
Revises: a4d856e9c7cf
Create Date: 2026-03-29 19:36:08.040942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deca24e15a01'
down_revision: Union[str, Sequence[str], None] = 'a4d856e9c7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

    op.drop_index('ix_unique_content_hash', table_name='documents')
    op.create_index(
        'ix_unique_content_hash',
        'documents',
        ['content_hash'],
        unique=True,
        postgresql_where=sa.text("status IN ('PROCESSING', 'AWAITING_REVIEW', 'APPROVED', 'INDEXING', 'COMPLETED')")
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_unique_content_hash', table_name='documents')
    op.create_index(
        'ix_unique_content_hash',
        'documents',
        ['content_hash'],
        unique=True,
        postgresql_where=sa.text("status IN ('PROCESSING', 'AWAITING_REVIEW', 'COMPLETED')")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
