"""add partial unique index for content hash

Revision ID: 95c755303d11
Revises: b0e7304861a8
Create Date: 2026-03-11 22:23:31.280011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c755303d11'
down_revision: Union[str, Sequence[str], None] = 'b0e7304861a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.create_index('ix_unique_content_hash', 'documents', ['content_hash'], unique=True, postgresql_where=sa.text("status IN ('PROCESSING', 'COMPLETED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_content_hash', table_name='documents', postgresql_where=sa.text("status IN ('PROCESSING', 'COMPLETED')"))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###
