"""add file hash to document

Revision ID: 331eaf756256
Revises: 95c755303d11
Create Date: 2026-03-12 15:12:06.316263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331eaf756256'
down_revision: Union[str, Sequence[str], None] = '95c755303d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
